import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import Link from "next/link";

export default function movieDetails({ detailsOfMovie }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Cine</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <link rel="icon" href="/favicon.ico" />

      <main className={styles.main}>
        <Link href="/">Home</Link>
        <Link href="/searchMovies"> Seach Movies</Link>
        <Link href="/about">About</Link>
        <h1 className={styles.title}>
          <span>{detailsOfMovie.title}</span>
        </h1>
        <p>Note: {detailsOfMovie.vote_average}</p>
        <h1 className={styles.title}>
          <span>Description:</span>
        </h1>
        <p>{detailsOfMovie.overview}</p>

        <img
          src={`https://image.tmdb.org/t/p/original${detailsOfMovie.backdrop_path}`}
          width="400"
        />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  let idOfMovie = context.params.id;
  const fetchingApi = await fetch(
    `http://localhost:3001/api/movie/${idOfMovie}`
  );
  const jsonOfFetchingApi = await fetchingApi.json();

  return {
    props: {
      detailsOfMovie: jsonOfFetchingApi.detailsOfMovie,
    },
  };
}
