import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home({ author }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Cine</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <link rel="icon" href="/favicon.ico" />

      <main className={styles.main}>
        <h1 className={styles.title}>About System</h1>
        <Link href="/">Home</Link>
        <Link href="/searchMovies"> Seach Movies</Link>
        <Link href="/about">About</Link>

        <h1>Description of system:</h1>
        <p>
          System that consumes a tmdb API, with featured movies listing, movie
          search, individual screen with more information about movies, and
          about screen.
        </p>
        <p>Author: {author}</p>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getStaticProps() {
  return {
    props: {
      author: "Anthony Lima",
    },
  };
}
