import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home({ list }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Cine</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <link rel="icon" href="/favicon.ico" />

      <main className={styles.main}>
        <h1 className={styles.title}>Featured Movies</h1>
        <Link href="/">Home</Link>
        <Link href="/searchMovies"> Seach Movies</Link>
        <Link href="/about">About</Link>
        <ul>
          {list.map((item) => (
            <li>
              <a href={`http://localhost:3001/movie/${item.id}`}>
                <img
                  src={`https://image.tmdb.org/t/p/original${item.poster_path}`}
                  width="150"
                />
                {item.title}
              </a>
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getServerSideProps() {
  const fetchingApi = await fetch("http://localhost:3001/api/trending");
  const jsonOfFetchingApi = await fetchingApi.json();
  return {
    props: {
      list: jsonOfFetchingApi.list,
    },
  };
}
