import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import Link from "next/link";
export default function SearchMovies({ list }) {
  const [searchText, setSearchText] = useState("");
  const [movieList, setMovieList] = useState([]);

  const handlerSearch = async () => {
    if (searchText !== "") {
      console.log("TEXTO", searchText);
      const fetchingApi = await fetch(
        `http://localhost:3001/api/searchMovies?searchText=${searchText}`
      );
      const jsonOfFetchingApi = await fetchingApi.json();
      setMovieList(jsonOfFetchingApi.list);
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Cine</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <link rel="icon" href="/favicon.ico" />

      <main className={styles.main}>
        <Link href="/">Home</Link>
        <Link href="/searchMovies"> Seach Movies</Link>
        <Link href="/about">About</Link>
        <h1 className={styles.title}>Search</h1>
        <input
          type="text"
          value={searchText}
          onChange={(e) => setSearchText(e.target.value)}
        />
        <span>Movie searched: {searchText} </span>
        <button onClick={handlerSearch}>search</button>
        <ul>
          {movieList.map((item) => (
            <li>
              <a href={`http://localhost:3001/movie/${item.id}`}>
                <img
                  src={`https://image.tmdb.org/t/p/original${item.poster_path}`}
                  width="150"
                />
                {item.title}
              </a>
            </li>
          ))}
        </ul>
      </main>
    </div>
  );
}
